'use client';
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { Provider } from 'react-redux';
import { store } from './store';

const chivo = Inter({ subsets: ["latin"], weight: ["400", "700"] });

/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Eco Guard App",
  description: "Generated by create next app",
};
*/


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Eco Guard App</title>
        <meta name="description" content="Generated by create next app" />
      </head>

      <body
        //className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={chivo.variable}
      >
        <Provider store={store}>{children}</Provider>
        
      </body>
    </html>
  );
}
